### ISSUE TITLE
[RediSearch] Add support for FT.CREATE & FT.SEARCH attributes

### ISSUE THREAD

**Issue by gkorland** [danitseitlin/redis-modules-sdk#100]
Two more features were added specific to JSON:

**On FT.CREATE:**

- identifier `AS` Attribute 

**On FT.SEARCH:**

- `RETURN` {jsonPath} `AS` {property}

**Comment by danitseitlin** [comment]
@gkorland Hi, thanks for the issue!
Are there any docs explaining these new additions?

**Comment by Mon0Man** [comment]
hey, there doesn't seem to be docs yet for JSON search support (https://github.com/RediSearch/RediSearch/issues/2043)
`AS` add alias for specified property. It seems you need to add alias on properties when creating index on JSON for many search features to work. 
Take at peek here as an example usage: https://youtu.be/6viyQCcdrU0?t=427

Thanks.
