### ISSUE TITLE
RediSearch - Add support for RETURN 0

### ISSUE THREAD

**Issue by Mon0Man** [danitseitlin/redis-modules-sdk#101]
Hello,  In the doc's for RETURN parameters it says:
"If num is 0, it acts like NOCONTENT " - https://oss.redislabs.com/redisearch/Commands/#ftsearch

There doesn't seem any way to do this with this modules, `return: { num: 0}` doesn't work.

maybe you can add support for this ? Thanks :)

**Comment by danitseitlin** [comment]
@Mon0Man Hi, thanks for your issue! I just fixed the issue and it will be released in the latest version of the NPM package.
If the issue persists, please let me know.
