### ISSUE TITLE
Adding Object based response for RediSearch

### ISSUE THREAD

**Issue by danitseitlin** [danitseitlin/redis-modules-sdk#33]
Today, RediSearch is returning complex responses that are not comfortable to handle/manage.

Solution:
Create a type/object that will hold this information

**Comment by dane-stevens** [comment]
@danitseitlin any thoughts on what this should look like?

Something like:

```javascript
[
  [
    {
      hash: 'movie:1001',
      title: 'Star Wars',
    }
  ],
  1
]
```

Could be destructured to:

```javascript
const [ results, count ] = await client.search('idx:movie', '*')
```

**Comment by danitseitlin** [comment]
@dane-stevens Not exactly.
The problem is we're getting a complex array with items of 1-4 levels and it makes it hard + annoying to maintain.
We have 2 approaches to think about:
1. Attempt to manipulate the output of the complex functions and build up a JS object. (the better solution) 
2. Return an actual object that holds a lot of information and has getter setter functions.

What do you think is a better solution? Got anymore ideas?
This should be thought carefully. 

P. S. The person performing this task should have a good grip on the Redisearch module (or at least dive strongly into the docs)

**Comment by danitseitlin** [comment]
@dane-stevens If this is urgent for you then let me know and I'll reprioritize.

**Comment by dane-stevens** [comment]
@danitseitlin It's not a huge priority right now. I can just parse the response myself for now. I only need one or two levels at most.

**Comment by danitseitlin** [comment]
@dane-stevens I'm currently working on adding the missing Redis AI module class after that I can handle this. If you want to give this task a try feel free to assign to yourself. Any contribution is welcome! If not - I'll syc here once I'll get to it

**Comment by danitseitlin** [comment]
@dane-stevens All done :)
