### ISSUE TITLE
Fix Redisearch tests 

### ISSUE THREAD

**Issue by danitseitlin** [danitseitlin/redis-modules-sdk#42]
The following tests are failing:

RediSearch Module testing
       alter function:
     Error: Redisearch: ReplyError: Duplicate field in schema
      at Redisearch.handleError (modules/module.base.ts:35:19)
      at Redisearch.<anonymous> (modules/redisearch.ts:294:25)
      at Generator.throw (<anonymous>)
      at rejected (modules/redisearch.ts:6:65)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  2) RediSearch Module testing
       tagvalgs function:
     Error: Redisearch: ReplyError: Not a tag field
      at Redisearch.handleError (modules/module.base.ts:35:19)
      at Redisearch.<anonymous> (modules/redisearch.ts:370:25)
      at Generator.throw (<anonymous>)
      at rejected (modules/redisearch.ts:6:65)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by dane-stevens** [comment]
@danitseitlin I'll take a look

**Comment by dane-stevens** [comment]
@danitseitlin I need a little clarification on the expected test results:

The `alter` and `tagvalgs` failing tests are related. 

Just to confirm I understand what is expected in the tests: 

1. The `alter` test is supposed to take the `name` field and convert from a `TEXT` to a `TAG` type. 
2. The `tagvalgs` test is returning the tags associated with the `name` field.

I believe what is happening is that the `FT.ALTER` command only adds new fields to the index and does not modify a field type based on the description of the command https://oss.redislabs.com/redisearch/Commands/#ftalter_schema_add. I don't have a ton of experience with RediSearch, so I may be misunderstanding the docs.

I'm able to get the tests passing if I modify the `alter` test to add a new field name instead and then update the `tagvalgs` to check the newly added field.

Here's an example:

```javascript
it('alter function', async () => {
    const response = await client.alter(index, 'test', 'TAG')
    expect(response).to.equal('OK', 'The response of the FT.ALTER command');
});
it('tagvalgs function', async () => {
    const response = await client.tagvals(index, 'test')
    expect(response.length).to.equal(0, 'The response of the FT.TAGVALS command')
});
```

**Comment by danitseitlin** [comment]
@dane-stevens First of all, thank you for all this amazing effort!
I believe what happened is because of your latest fixes, the functions started functioning better which caused the test to attempt and alter an existing tag. This kind of solution will be fine by me.
The whole idea of the tests is to verify some kind of E2E Integration between the module itself.
🔥
