### ISSUE TITLE
Running testcafe test in latest version (0.5.1) fails with 'Error: TypeScript compilation failed.'

### ISSUE THREAD

**Issue by michaelk-redis** [danitseitlin/redis-modules-sdk#80]
running testcafe test, that uses import of ReJSON, Redisearch, RedisBloom, RedisGraph, RTS, GraphConfigInfo from 'redis-modules-sdk' fails with error:
Error: TypeScript compilation failed.
node_modules/redis-modules-sdk/lib/modules/redis.d.ts (46, 28): ']' expected.
node_modules/redis-modules-sdk/lib/modules/redis.d.ts (46, 42): ';' expected.
node_modules/redis-modules-sdk/lib/modules/redis.d.ts (46, 43): Declaration or statement expected.
node_modules/redis-modules-sdk/lib/modules/redis.d.ts (47, 1): Declaration or statement expected.

**Comment by michaelk-redis** [comment]
Downgarding to 0.5.0 version of sdk eliminates the issue

**Comment by danitseitlin** [comment]
@michaelk-redis Hi, thanks for the issue.
I was able to reproduce the issue, the issue should not be fixed in version 0.5.2.
Please let me know if the issue still occurs.
Thanks ✌🏽

**Comment by michaelk-redis** [comment]
@danitseitlin you rock!
