### ISSUE TITLE
RedisBloom: Support for T-Digest data structure

### ISSUE THREAD

**Issue by filipecosta90** [danitseitlin/redis-modules-sdk#82]
Given https://github.com/RedisBloom/RedisBloom/pull/285 there is the following set of commands we should enable:

  - `TDIGEST.CREATE`: Allocate a new histogram
  - `TDIGEST.RESET`: Empty out a histogram and re-initialize it
  - `TDIGEST.ADD`: Add a value to the t-Digest with the specified count
  - `TDIGEST.MERGE`: Merge one t-Digest into another
  - `TDIGEST.CDF`:  Returns the fraction of all points added which are &le; x.
  - `TDIGEST.QUANTILE`: Returns an estimate of the cutoff such that a specified fraction of the data added to the t-Digest would be less than or equal to the cutoff.
  - `TDIGEST.MIN`: Get the minimum value from the histogram.  Will return __DBL_MAX__ if the histogram is empty
  - `TDIGEST.MAX`: Get the maximum value from the histogram.  Will return __DBL_MIN__ if the histogram is empty
  - `TDIGEST.INFO` : Returns compression, capacity, total merged and unmerged nodes, the total compressions 
made up to date on that key, and merged and unmerged weight.

With the in-depth params in https://oss.redislabs.com/redisbloom/master/TDigest_Commands/

**Comment by danitseitlin** [comment]
@filipecosta90 Hi, thank you for the pointer! will be on it in the next few days 🌟

**Comment by filipecosta90** [comment]
Thank you for the fast replies and additions @danitseitlin 👏 👏

**Comment by danitseitlin** [comment]
@filipecosta90 Using the rebloom:latest docker img I am getting errors here: https://github.com/danitseitlin/redis-modules-sdk/runs/2487335516?check_suite_focus=true
Was this not pushed yet?

**Comment by filipecosta90** [comment]
@danitseitlin if you use the `rebloom:edge` the commands should be there.
