### ISSUE TITLE
Update RedisAI API

### ISSUE THREAD

**Issue by DvirDukhan** [danitseitlin/redis-modules-sdk#83]
note that we are making changes to RedisAI commands
the following commands will be deprecated and you should use the new command:
`MODELSET` -> `MODELSTORE` https://oss.redislabs.com/redisai/master/commands/#aimodelstore
`MODELRUN` -> `MODELEXECUTE` https://oss.redislabs.com/redisai/master/commands/#aimodelexecute
`SCRIPTRUN` -> `SCRIPTEXECUTE` open for review - https://github.com/RedisAI/RedisAI/pull/682
`DAGRUN` -> `DAGEXECUTE`

**Comment by danitseitlin** [comment]
@DvirDukhan Hi, thanks for the issue. I have a few questions:
1. From what version should the change be considered?
2. In your opinion, should I keep the deprecated functions and mention they are deprecated? Will it be logical that a customer use an older version of RedisAI?

**Comment by danitseitlin** [comment]
@DvirDukhan I appreciate your issue and acknowledgement. This is now merged.
