### ISSUE TITLE
Set data wipe policy

### ISSUE THREAD

**Issue by YashKumarVerma** [danitseitlin/redis-modules-sdk#86]
I have not configured the sdk to wipe data from the storage (`TTL` in redis), but the data that I store in the container (written via the sdk interface)) is wiped after regular intervals of time.

I am sure that this is not a problem with the container as the container has not crashed since launch.

**Comment by YashKumarVerma** [comment]
Thanks a lot for quick reply, here's some info that can help.
Modules Used: **Redis-JSON**

Connection Declaration:
```js
import { ReJSON } from 'redis-modules-sdk/lib/modules/rejson'

const jsonClient = new ReJSON({
  host: config.get('cache.host'),
  port: config.get('cache.port'),
})

export { jsonClient }
```

This is how I inserted the data into the store.
```js
import { jsonClient } from '../../services/redis/reJSON'

static async create(team:...): Promise<...> {
    const document = { friendlyName, id, devices: [] }

    const query = await jsonClient.set(`team:${team.id}`, '.', JSON.stringify(document))
    if (query === 'OK') {
      return document
    }

  }
```

## Live Example:
As of now, this is the data that's there on the API: URL->http://40.119.165.213:8000/team
![https://i.imgur.com/SFkENju.png](https://i.imgur.com/SFkENju.png)

I'll keep an eye and let you know when it disappears.

**Comment by YashKumarVerma** [comment]
update: vanished in about 1 hour

**Comment by danitseitlin** [comment]
@YashKumarVerma Well, this is kind of odd. In the SDK, the function of `.set` sets a key, path and it's json contents. It does not handle TTL at all. If you refer to the original command of `JSON.SET` it also does not handle TTL from what I can see.
I believe this is a question for the repository of REJSON module, https://github.com/RedisJSON/RedisJSON

**Comment by YashKumarVerma** [comment]
Alright then, I'm closing this issue.

Thank you for your time, it's an awesome piece of work 👍🏼
